spring:
  application:
    name: shelflife

  data:
    redis:
      host: "redis-15990.c242.eu-west-1-2.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 15990
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    #This is a connection pool configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAIL_WITH_BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: stingray-01.rmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: shezckfv
    ssl:
      enabled: true
    virtual-host: shezckfv
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2
          max-retries: 3

jwt:
  secret: ${JWT_SECRET_BASE64}

shelflife:
  api-key:
    expires-in-days: 365
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  auth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}

  email:
    from: esekaemmanuel017@gmail.com # I'll keep using this for now until I buy the domain for Brevo
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on the same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://olcrsrqkaddupxeseskr.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

server:
  port: 8080