spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.olcrsrqkaddupxeseskr

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp-relay.brevo.com
    username: a130b3001@smtp-brevo.com

jwt:
  expiration-minutes: 1000

shelflife:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false

nginx:
  require-proxy: false

logging:
  level:
    com.eeseka.shelflife: DEBUG