spring:
  datasource:
    url: jdbc:postgresql://db.olcrsrqkaddupxeseskr.supabase.co:5432/postgres?sslmode=require
    username: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp-relay.brevo.com
    username: a130b3001@smtp-brevo.com

jwt:
  expiration-minutes: 15

shelflife:
  email:
    url: "https://myshelflifeapp.com"
  rate-limit:
    ip:
      apply-limit: true

nginx:
  require-proxy: false

logging:
  level:
    com.eeseka.shelflife: INFO